apiVersion: v1
kind: Pod
metadata:
  name: java03
  labels:
    app: demo-app
spec:
  containers:
  - name: java-c1
    image: shindevaibhavi11/java03:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
